# Create an Autoscaling group for our node app



apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler #(hpa)

metadata:
  name: sparta-mongo-db-deploy
  namespace: default
  
spec:
  maxReplicas: 6 #(max nuber of instances/pods)
  minReplicas: 3 #(min nuber of instances/pods)
  scaleTargetRef: # Targets the node deployment
    apiVersion: apps/v1
    kind: Deployment
    name: mongodb
  targetCPUUtilizationPercentage: 50  # 50% of CPU use