---


apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb

  replicas: 3

  template:
    metadata:
      labels:
        app: mongodb

    spec:
      containers:
      - name: mongodb
        image: ellieckay/tech241-mongodb:v1
        ports:
        - containerPort: 27017